# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.1.2

# NeoForge
neo_version=26.1.2.41-beta

# Fabric
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.148.0+26.1.2

# Mod metadata
mod_id=sacred_trees
mod_name=Sacred Trees
mod_version=1.1.0
mod_group=io.bluebeaker.sacred_trees
mod_license=All Rights Reserved
mod_author=Blue_Beaker
mod_description=Brings the Sacred Rubber Tree from Minefactory Reloaded back!\nAdds Mega, Sacred and Enchanted Sacred saplings for every vanilla trees, including fungus.